%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\aProjects\ContentDevelopment\ElectrificationEnthusiasts\PowerQuality\MatlabBased\power_quality_data.csv
%
% Auto-generated by MATLAB on 09-Jan-2025 11:32:32

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "i_dc", "i_a"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
powerqualitydata = readtable("C:\aProjects\ContentDevelopment\ElectrificationEnthusiasts\PowerQuality\MatlabBased\power_quality_data.csv", opts);

%% Convert to output type
powerqualitydata = table2array(powerqualitydata);

%% Clear temporary variables
clear opts